name: Build ConsoleApp
on:
    push:
    pull_request:

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        env:
            DOTNET_NOLOGO: true
        
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            
            - name: Setup .NET SDK
              uses: actions/setup-dotnet@v4
              with:
                global-json-file: global.json
            
            - name: Run dotnet restore
              run: |
                dotnet restore ./ConsoleApp/
            
            - name: Run dotnet build
              run: |
                dotnet build ./ConsoleApp/