name: Generate PNGs

on:
    schedule:
      - cron: '30 13 * * 1'
    workflow_dispatch:

jobs:
    build:
        name: Compile TwemojiConverter
        uses: ./.github/workflows/compile-consoleapp.yml
        with:
          ref: "v0.2.1"

    convert:
        name: Convert to PNGs
        needs: build
        runs-on: ubuntu-latest
        strategy:
          matrix:
            image-size: [ 128, 256, 512 ]
        
        steps:
            - name: Download compiled binary
              uses: actions/download-artifact@v4
              with:
                name: twemoji-converter-linux-x64
                path: ${{ github.workspace }}/tool/
            
            - name: Clone Twemoji repo
              uses: actions/checkout@v4
              with:
                repository: discord/twemoji
                path: twemoji

            - name: Enable executable permissions
              run: |
                chmod +x ./tool/twemoji-converter

            - name: Run converter
              run: |
                ./tool/twemoji-converter convert --svg-directory "./twemoji/assets/svg/" --output-directory "./converted/" --output-resolution ${{ matrix.image-size }} ; ./tool/twemoji-converter get-info --output-path "./converted/_emojiList.json" --image-directory-path "./converted/"

            - name: Upload converted PNGs
              uses: actions/upload-artifact@v4
              with:
                name: discord-twemoji-png-${{ matrix.image-size }}
                path: ${{ github.workspace }}/converted/**/*
                if-no-files-found: error

            